### ISSUE TITLE
Update to make this better

### ISSUE THREAD

**Issue by huytbt** [mageplaza/magento-2-vietnamese-language-pack#2]

**Comment by huytbt** [comment]
Hi @imsamthomas,

Can you please add me to contributor list.
I want to contribute to update language.

Thank you

**Comment by imsamthomas** [comment]
Hi @huytbt 

You can contribute the project at https://crowdin.com/project/magento-2/vi
It will automatically pull to Mageplaza repo

Regards,
Sam

**Comment by huytbt** [comment]
Thank you @imsamthomas
